config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :locations
  resources :weathers
  resources :expenses
  resources :incomes
  resources :breeds
  resources :eggs
  resources :animals
  resources :farms
  resources :trends
  post 'inventories/incrementanimal', to: 'inventories#incrementanimal', as: "incrementanimal"
  post 'inventories/decrementanimal', to: 'inventories#decrementanimal', as: "decrementanimal"
  post 'inventories/incrementegg', to: 'inventories#incrementegg', as: "incrementegg"
  post 'inventories/decrementegg', to: 'inventories#decrementegg', as: "decrementegg"
  resources :inventories

  root 'farms#index'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :farm
  has_many :eggs
end

app/models/egg.rb
class Egg < ActiveRecord::Base
  belongs_to :animal
  has_many :incomes
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :farm
end

app/models/farm.rb
class Farm < ActiveRecord::Base
  has_many :expenses
  has_many :incomes
  has_many :animals
  has_many :eggs, through: :animals
  has_many :weathers
  has_many :users
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :farm
  belongs_to :egg
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :animals
  has_many :eggs
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :farm
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/weather.rb
class Weather < ActiveRecord::Base
  belongs_to :farm
end

app/controllers/eggs_controller.rb
class EggsController < ApplicationController
skip_before_action :verify_authenticity_token
  before_action :set_egg, only: [:show, :edit, :update, :destroy]


  # GET /eggs
  def index
    @egg = Egg.all
    @egginventory = Inventory.all
    @eggtimer = Inventory.all
    @inventory = Inventory.new
  end


  # POST /eggs
  def create
    @egg = Egg.new(egg_params)
    @egg.save
    flash[:notice] = "Egg count recorded!"
    redirect_to :back
  end


  # PATCH  /eggs/:id(.:format)  eggs#update
  def edit
    @egg = Egg.find(@egg.id).increment!(:quantity)
    update_attributes(:quantity => quantity + 1)
    flash[:notice] = "One added to egg count"
    redirect_to :back
  end


  # DELETE /eggs/1
  def destroy
    @egg.destroy
    flash[:notice] = "Egg count was successfully destroyed."
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_egg
      @egg = Egg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def egg_params
      params.require(:egg).permit(:color, :quantity, :animal_id)
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  # GET /farms
  # GET /farms.json
  def index
    @farms = Farm.all
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = Farm.new(farm_params)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms/1
  # PATCH/PUT /farms/1.json
  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm.destroy
    respond_to do |format|
      format.html { redirect_to farms_url, notice: 'Farm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farm_params
      params.require(:farm).permit(:animal_id, :income_id, :expense_id, :weather_id)
    end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
    @expense = Expense.all
    @income = Income.all
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def incrementegg
    @column = params[:eggtype]
    @row = Inventory.find(params[:id])
    @currentcount = @row[@column] + 1
    @row[@column] = @currentcount
    @row.save
    # notice[:flash] "one egg added"
    redirect_to :back
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def decrementegg
    @column = params[:eggtype]
    @row = Inventory.find(params[:id])
    @currentcount = @row[@column] - 1
    @row[@column] = @currentcount
    @row.save
    # notice[:flash] "one egg added"
    redirect_to :back
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end


   # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def incrementanimal
    @column = params[:animaltype]
    @row = Inventory.find(params[:id])
    @currentcount = @row[@column] + 1
    @row[@column] = @currentcount
    @row.save
    # notice[:flash] "one animal added"
    redirect_to :back
  end


  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def decrementanimal
    @column = params[:animaltype]
    @row = Inventory.find(params[:id])
    @currentcount = @row[@column] - 1
    @row[@column] = @currentcount
    @row.save
    # notice[:flash] "one animal added"
    redirect_to :back
  end


  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.save
    flash[:notice] = "Added!"
    redirect_to :back
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
     def inventory_params
      params.require(:inventory).permit(:chickenltbrownlayer, :chickendrkbrnlayer, :chickenwhitelayer, :chickenblugrnlayer, :chickenbantamlayer, :duck, :goose, :turkey, :guinea, :quail, :chickenltbrownegg, :chickendrkbrnegg, :chickenwhiteegg, :chickenblugrnegg, :chickenbantamegg, :duckegg, :gooseegg, :turkeyegg, :guineaegg, :quailegg)
    end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  def index
    @eggs = Inventory.all
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/eggs_helper.rb
module EggsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- LAYERS -->
  <div class="field">
    <%= f.label :chickenltbrownlayer %><br>
    <%= f.number_field :chickenltbrownlayer, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :chickendrkbrnlayer %><br>
    <%= f.number_field :chickendrkbrnlayer, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :chickenwhitelayer %><br>
    <%= f.number_field :chickenwhitelayer, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :chickenblugrnlayer %><br>
    <%= f.number_field :chickenblugrnlayer, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :chickenbantamlayer %><br>
    <%= f.number_field :chickenbantamlayer, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :duck %><br>
    <%= f.number_field :duck, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :goose %><br>
    <%= f.number_field :goose, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :turkey %><br>
    <%= f.number_field :turkey, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :guinea %><br>
    <%= f.number_field :guinea, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :quail %><br>
    <%= f.number_field :quail, min: 0 %>
  </div>

  <!-- EGGS -->
  <div class="field">
    <%= f.label :chickenltbrownegg %><br>
    <%= f.number_field :chickenltbrownegg %>
  </div>
  <div class="field">
    <%= f.label :chickendrkbrnegg %><br>
    <%= f.number_field :chickendrkbrnegg %>
  </div>
  <div class="field">
    <%= f.label :chickenwhiteegg %><br>
    <%= f.number_field :chickenwhiteegg %>
  </div>
  <div class="field">
    <%= f.label :chickenblugrnegg %><br>
    <%= f.number_field :chickenblugrnegg %>
  </div>
  <div class="field">
    <%= f.label :chickenbantamegg %><br>
    <%= f.number_field :chickenbantamegg %>
  </div>
  <div class="field">
    <%= f.label :duckegg %><br>
    <%= f.number_field :duckegg %>
  </div>
  <div class="field">
    <%= f.label :gooseegg %><br>
    <%= f.number_field :gooseegg %>
  </div>
  <div class="field">
    <%= f.label :turkeyegg %><br>
    <%= f.number_field :turkeyegg %>
  </div>
  <div class="field">
    <%= f.label :guineaegg %><br>
    <%= f.number_field :guineaegg %>
  </div>
  <div class="field">
    <%= f.label :quailegg %><br>
    <%= f.number_field :quailegg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/_form_animals.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- LAYERS -->
  <div class="field">
    <%= f.label :chickenltbrownlayer %><br>
    <%= f.number_field :chickenltbrownlayer %>
  </div>
  <div class="field">
    <%= f.label :chickendrkbrnlayer %><br>
    <%= f.number_field :chickendrkbrnlayer %>
  </div>
  <div class="field">
    <%= f.label :chickenwhitelayer %><br>
    <%= f.number_field :chickenwhitelayer %>
  </div>
  <div class="field">
    <%= f.label :chickenblugrnlayer %><br>
    <%= f.number_field :chickenblugrnlayer %>
  </div>
  <div class="field">
    <%= f.label :chickenbantamlayer %><br>
    <%= f.number_field :chickenbantamlayer %>
  </div>
  <div class="field">
    <%= f.label :duck %><br>
    <%= f.number_field :duck %>
  </div>
  <div class="field">
    <%= f.label :goose %><br>
    <%= f.number_field :goose %>
  </div>
  <div class="field">
    <%= f.label :turkey %><br>
    <%= f.number_field :turkey %>
  </div>
  <div class="field">
    <%= f.label :guinea %><br>
    <%= f.number_field :guinea %>
  </div>
  <div class="field">
    <%= f.label :quail %><br>
    <%= f.number_field :quail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/_form_eggs.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% @inventory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- EGGS -->
  <div class="input-field col s12 brown lighten-5">
    <%= f.label "# Chicken Eggs: Light Brown" %>
    <%= f.number_field :chickenltbrownegg %>
  </div>

  <div class="input-field col s12 brown lighten-4">
    <%= f.label "# Chicken Eggs: Dark Brown" %>
    <%= f.number_field :chickendrkbrnegg %>
  </div>

  <div class="input-field col s12">
    <%= f.label "# Chicken: White" %><br>
    <%= f.number_field :chickenwhiteegg %>
  </div>

  <div class="input-field col s12 teal lighten-5">
    <%= f.label "# Chicken Eggs: Blu/Grn" %>
    <%= f.number_field :chickenblugrnegg %>
  </div>

  <div class="input-field col s12">
    <%= f.label "# Chicken Eggs: Bantam" %>
    <%= f.number_field :chickenbantamegg %>
  </div>

  <div class="input-field col s12 green lighten-5">
    <%= f.label "# Duck Eggs" %>
    <%= f.number_field :duckegg %>
  </div>

  <div class="input-field col s12">
    <%= f.label "# Goose Eggs" %>
    <%= f.number_field :gooseegg %>
  </div>

  <div class="input-field col s12 orange lighten-5">
    <%= f.label "# Turkey Eggs" %>
    <%= f.number_field :turkeyegg %>
  </div>

  <div class="input-field col s12 brown lighten-5">
    <%= f.label "# Guinea Hen Eggs" %>
    <%= f.number_field :guineaegg %>
  </div>

  <div class="input-field col s12 brown lighten-4">
    <%= f.label "# Quail Eggs" %>
    <%= f.number_field :quailegg %>
  </div>


  <%= f.submit 'ENTER COUNT', :class => 'willbtn-submit' %>
  <% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inventories</h1>

<table>
  <thead>
    <tr>
      <th>Entry Date</th>
      <th>Chicken Lt Brown Layer</th>
      <th>Chicken Drk Brown Layer</th>
      <th>Chicken White Layer</th>
      <th>Chicken Blu/Grn Layer</th>
      <th>Chicken Bantam Layer</th>
      <th>Duck</th>
      <th>Goose</th>
      <th>Turkey</th>
      <th>Guinea</th>
      <th>Quail</th>
      <th>Chicken Lt Brown Egg</th>
      <th>Chicken Drk Brown Egg</th>
      <th>Chicken White Egg</th>
      <th>Chicken Blu/Grn Egg</th>
      <th>Chicken Bantam Egg</th>
      <th>Duck Egg</th>
      <th>Goose Egg</th>
      <th>Turkey Egg</th>
      <th>Guinea Egg</th>
      <th>Quail Egg</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.created_at.strftime("%D") %></td>
        <td><%= inventory.chickenltbrownlayer %></td>
        <td><%= inventory.chickendrkbrnlayer %></td>
        <td><%= inventory.chickenwhitelayer %></td>
        <td><%= inventory.chickenblugrnlayer %></td>
        <td><%= inventory.chickenbantamlayer %></td>
        <td><%= inventory.duck %></td>
        <td><%= inventory.goose %></td>
        <td><%= inventory.turkey %></td>
        <td><%= inventory.guinea %></td>
        <td><%= inventory.quail %></td>
        <td><%= inventory.chickenltbrownegg %></td>
        <td><%= inventory.chickendrkbrnegg %></td>
        <td><%= inventory.chickenwhiteegg %></td>
        <td><%= inventory.chickenblugrnegg %></td>
        <td><%= inventory.chickenbantamegg %></td>
        <td><%= inventory.duckegg %></td>
        <td><%= inventory.gooseegg %></td>
        <td><%= inventory.turkeyegg %></td>
        <td><%= inventory.guineaegg %></td>
        <td><%= inventory.quailegg %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chicken:</strong>
  <%= @inventory.chicken %>
</p>

<p>
  <strong>Duck:</strong>
  <%= @inventory.duck %>
</p>

<p>
  <strong>Goose:</strong>
  <%= @inventory.goose %>
</p>

<p>
  <strong>Turkey:</strong>
  <%= @inventory.turkey %>
</p>

<p>
  <strong>Guinea:</strong>
  <%= @inventory.guinea %>
</p>

<p>
  <strong>Quail:</strong>
  <%= @inventory.quail %>
</p>

<p>
  <strong>Brown:</strong>
  <%= @inventory.brown %>
</p>

<p>
  <strong>White:</strong>
  <%= @inventory.white %>
</p>

<p>
  <strong>Blue:</strong>
  <%= @inventory.blue %>
</p>

<p>
  <strong>Drkbrn:</strong>
  <%= @inventory.drkbrn %>
</p>

<p>
  <strong>Speckled:</strong>
  <%= @inventory.speckled %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>