config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :locations
  resources :weathers
  resources :expenses
  resources :incomes
  resources :breeds
  resources :eggs
  resources :animals
  resources :farms
  resources :trends
  post 'inventories/incrementanimal', to: 'inventories#incrementanimal', as: "incrementanimal"
  post 'inventories/decrementanimal', to: 'inventories#decrementanimal', as: "decrementanimal"
  post 'inventories/incrementegg', to: 'inventories#incrementegg', as: "incrementegg"
  post 'inventories/decrementegg', to: 'inventories#decrementegg', as: "decrementegg"
  resources :inventories

  root 'farms#index'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :farm
  has_many :eggs
end

app/models/egg.rb
class Egg < ActiveRecord::Base
  belongs_to :animal
  has_many :incomes
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :farm
end

app/models/farm.rb
class Farm < ActiveRecord::Base
  has_many :expenses
  has_many :incomes
  has_many :animals
  has_many :eggs, through: :animals
  has_many :weathers
  has_many :users
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :farm
  belongs_to :egg
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :animals
  has_many :eggs
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :farm
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/weather.rb
class Weather < ActiveRecord::Base
  belongs_to :farm
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]


  # GET /animals
  def index
    @animal = Animal.all
    @animalinventory = Inventory.all
    @animaltime = Inventory.all
    @inventory = Inventory.new
  end


  # GET /animals/1
  # GET /animals/1.json
  def show
  end


  # GET /animals/new
  def new
    @animal = Animal.new
  end


 # POST /animals
  def create
    @animal = Animal.new(egg_params)
    @animal.save
    flash[:notice] = "Flock category created!"
    redirect_to :back
  end


 # PATCH  /animals/:id(.:format)  animals#update
  def edit
    @animal = Animal.find(@animal.id).increment!(:quantity)
    update_attributes(:quantity => quantity + 1)
    flash[:notice] = "One bird added to this flock"
    redirect_to :back
  end


  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)
    flash[:notice] = "New animal created"
    redirect_to :back
  end


  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    @animal.update(animal_params)
    flash[:notice] = "One animal added"
    redirect_to :back
  end


  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    flash[:notice] = "Animal type removed."
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:id, :name, :breed_id, :egg_id)
    end
end

app/controllers/eggs_controller.rb
class EggsController < ApplicationController
skip_before_action :verify_authenticity_token
  before_action :set_egg, only: [:show, :edit, :update, :destroy]


  # GET /eggs
  def index
    @egg = Egg.all
    @egginventory = Inventory.all
    @eggtimer = Inventory.all
    @inventory = Inventory.new
  end


  # POST /eggs
  def create
    @egg = Egg.new(egg_params)
    @egg.save
    flash[:notice] = "Egg count recorded!"
    redirect_to :back
  end


  # PATCH  /eggs/:id(.:format)  eggs#update
  def edit
    @egg = Egg.find(@egg.id).increment!(:quantity)
    update_attributes(:quantity => quantity + 1)
    flash[:notice] = "One added to egg count"
    redirect_to :back
  end


  # DELETE /eggs/1
  def destroy
    @egg.destroy
    flash[:notice] = "Egg count was successfully destroyed."
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_egg
      @egg = Egg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def egg_params
      params.require(:egg).permit(:color, :quantity, :animal_id)
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  # GET /farms
  # GET /farms.json
  def index
    @farms = Farm.all
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = Farm.new(farm_params)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms/1
  # PATCH/PUT /farms/1.json
  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm.destroy
    respond_to do |format|
      format.html { redirect_to farms_url, notice: 'Farm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farm_params
      params.require(:farm).permit(:animal_id, :income_id, :expense_id, :weather_id)
    end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  def index
    @eggs = Inventory.all
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/eggs_helper.rb
module EggsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/animals/index.html.erb
<br>
<div class="container white z-depth-1">
    <div class="center-align">
      <div class="row">
        <div class="col s12 brown z-depth-1">
          <span class="whiteit-title">FLOCKS CURRENTLY ON FARM</span>
        </div>
      </div>
    </div>
    <div class="inventory-box">
      <div class="col 12">
        <div class="row">
          <table class="bordered responsive grey lighten-4">
            <thead>
              <tr>
                <th>Date</th>
                <th>Layer Variety</th>
                <th>Quantity</th>
                <th>Plus</th>
                <th>Less</th>
                <th>Remove</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>07/23/15</td>
                <td>Chickens: Lt Brn Eggs</td>
                <td><%= @animalinventory.last.chickenltbrownlayer %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenltbrownlayer" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenltbrownlayer" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Chickens: Dk Brn Eggs</td>
                <td><%= @animalinventory.last.chickendrkbrnlayer %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "chickendrkbrnlayer" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "chickendrkbrnlayer" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Chickens: White Eggs</td>
                <td><%= @animalinventory.last.chickenwhitelayer %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenwhitelayer" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenwhitelayer" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Chickens: Blu/Grn Eggs</td>
                <td><%= @animalinventory.last.chickenblugrnlayer %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenblugrnlayer" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenblugrnlayer" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Chickens: Bantam</td>
                <td><%= @animalinventory.last.chickenbantamlayer %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenbantamlayer" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "chickenbantamlayer" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Ducks</td>
                <td><%= @animalinventory.last.duck %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "Duck" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "Duck" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Geese</td>
                <td><%= @animalinventory.last.goose %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "goose" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "goose" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Turkeys</td>
                <td><%= @animalinventory.last.turkey %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "turkey" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "turkey" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Guinea Hens</td>
                <td><%= @animalinventory.last.guinea %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "guinea" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "guinea" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
               <tr>
                <td>07/23/15</td>
                <td>Quail</td>
                <td><%= @animalinventory.last.quail %></td>
                <td>
                  <%= button_to "+1", incrementanimal_path({id: @animalinventory.last.id, animaltype: "quail" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementanimal_path({id: @animalinventory.last.id, animaltype: "quail" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Remove", "animals/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<br>

app/views/eggs/archive_index.html.erb
<br>
<div class="container white z-depth-1">
  <div class="center-align">
    <div class="row">
      <div class="col s12 orange z-depth-1">
        <span class="whiteit-title">Let's Count Some Eggs!</span>
      </div>
    </div>
  </div>

  <div class="container">
  <br>
  <br>

    <div class="row">

    <!-- SPACER COLUMN -->
      <div class="col s3"><span class="make-invisible">.</span></div>

          <!-- ENTRY FIELDS -->
          <div class="col s6">


<%= render(:partial => "inventories/form_eggs") %>


            <form action="/eggs" method="post">
              <div class="row">
                <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

                  <div class="input-field col s12 brown lighten-5">
                    <input value="number" id="chickenltbrnegg" name="inventory[:id]" type="number" class="validate">
                    <label for="chickenltbrnegg"># Chicken: Lt Brown</label>
                  </div>
                </div>
              <br>
              <div class="row">

                  <div class="input-field col s12 brown lighten-4">
                    <input value="number" id="chickendrkbrnegg" name="inventory[:id]" type="number" class="validate">
                    <label for="chickendrkbrnegg"># Chicken: Drk Brown</label>
                  </div>
                </div>
              <br>
              <div class="row">



                  <div class="input-field col s12">
                    <input value="number" id="chickenwhiteegg" name="inventory[:id]" type="number" class="validate">
                    <label for="chickenwhiteegg"># Chicken: White</label>
                  </div>
                </div>


              <br>
              <div class="row">

                  <div class="input-field col s12 teal lighten-5">
                    <input value="number" id="chickenblugrnegg" name="inventory[:id]" type="number" class="validate">
                    <label for="chickenblugrnegg"># Chicken: Blue/Green</label>
                  </div>
                </div>
              <br>
              <div class="row">

                  <div class="input-field col s12 green lighten-5">
                    <input value="number" id="duckegg" name="inventory[:id]" type="number" class="validate">
                    <label for="duckegg"># Duck Eggs</label>
                  </div>
                </div>
              <br>
              <div class="row">

                  <div class="input-field col s12">
                    <input value="number" id="gooseegg" name="inventory[:id]" type="number" class="validate">
                    <label for="gooseegg"># Goose Eggs</label>
                  </div>
                </div>
              <br>
              <div class="row">

                  <div class="input-field col s12 orange lighten-5">
                    <input value="number" id="turkeyegg" name="inventory[:id]" type="number" class="validate">
                    <label for="turkeyegg"># Turkey Eggs</label>
                  </div>
                </div>
              <br>
              <div class="row">

                  <div class="input-field col s12 brown lighten-5">
                    <input value="number" id="guineaeggs" name="inventory[:id]" type="number" class="validate">
                      <label for="guineaeggs"># Guinea Eggs</label>
                  </div>
                </div>
              <br>
              <div class="row">

                  <div class="input-field col s12 brown lighten-4">
                    <input value="number" id="quaileggs" name="inventory[:id]" type="number" class="validate">
                      <label for="quaileggs"># Quail Eggs</label>
                  </div>
                </div>
              </form>
            <br>
          </div>

        <!-- SPACER COLUMN -->
        <div class="col s3"><span class="make-invisible">.</span></div>

        <!-- SUBMIT BUTTON -->
        <div class="row">
          <div class="centerize-field">
            <div class="input-field col s12">
              <button class="btn waves-effect waves-orange" type="submit" name="action">Submit</button>
            </div>
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>

        <br>
        <br>
    </div>
  </div>


<!-- EGG INVENTORY -->
  <div class="container white z-depth-1">
    <div class="center-align">
      <div class="row">
        <div class="col s12 orange z-depth-1">
          <span class="whiteit-title">Eggs Currently In Inventory</span>
        </div>
      </div>
    </div>
    <div class="inventory-box">
      <div class="col 12">
        <div class="row">
          <table class="bordered responsive">
            <thead>
              <tr>
                <th>Id</th>
                <th>Laid By</th>
                <th>Quantity</th>
                <th>Add</th>
                <th>Subtract</th>
                <th>Remove Flock</th>
              </tr>
            </thead>

            <tbody><% @egg.each do |egg| %>
              <tr>
                <td><%= egg.id %></td>
                <td><%= egg.animal_id %></td>
                <td><%= Egg.where(id: egg.id).count %></td>

                <!-- ADD EGG BUTTON -->
                <td><button class="btn light-blue">
                  <%= link_to '+1', edit_egg_path(egg) %></button></td>

                <!-- SUBTRACT EGG BUTTON -->
                <td><button class="btn orange darken-2">
                  <%= link_to '-1', edit_egg_path(egg) %></button></td>

                <!-- REMOVE ENTRY BUTTON -->
                <td><button class="btn red">
                  <%= link_to 'Remove Eggs', egg, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>

              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<br>

app/views/eggs/index.html.erb
<br>
<div class="container white z-depth-1">
  <div class="center-align">
    <div class="row">
      <div class="col s12 orange z-depth-1">
        <span class="whiteit-title">ENTER TODAY'S EGG COUNT</span>
      </div>
    </div>
  </div>
  <div class="container">
  <br>
  <br>
    <div class="row">

    <!-- SPACER COLUMN -->
      <span class="make-invisible col s3">.</span>

      <!-- EGG ENTRY PARTIAL -->
      <div class="col s6">
        <%= render(:partial => "inventories/form_eggs") %>
      </div>
    </div>
    <br>
  </div>
</div>
<br>
<br>

<!-- LATEST EGG COUNT -->
  <div class="container white z-depth-1">
    <div class="center-align">
      <div class="row">
        <div class="col s12 orange z-depth-1">
          <span class="whiteit-title">VIEW/ADJUST LATEST EGG COUNT</span>
        </div>
      </div>
    </div>
    <div class="inventory-box">
      <div class="col 12">
        <div class="row">
          <table class="bordered responsive grey lighten-4">
            <thead>
              <tr>
                <th>Date</th>
                <th>Egg Variety</th>
                <th>Quantity</th>
                <th>Plus</th>
                <th>Less</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>07/23/15</td>
                <td>Chicken Eggs: Light Brown</td>
                <td><%= @egginventory.last.chickenltbrownegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "chickenltbrownegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "chickenltbrownegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>

              <tr>
                <td>07/23/15</td>
                <td>Chicken Eggs: Dark Brown</td>
                <td><%= @egginventory.last.chickendrkbrnegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "chickendrkbrnegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "chickendrkbrnegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Chicken Eggs: White</td>
                <td><%= @egginventory.last.chickenwhiteegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "chickenwhiteegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "chickenwhiteegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Chicken Eggs: Blu/Grn</td>
                <td><%= @egginventory.last.chickenblugrnegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "chickenblugrnegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "chickenblugrnegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Chicken Eggs: Bantam</td>
                <td><%= @egginventory.last.chickenbantamegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "chickenbantamegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "chickenbantamegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Duck Eggs</td>
                <td><%= @egginventory.last.duckegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "duckegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "duckegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Goose Eggs</td>
                <td><%= @egginventory.last.gooseegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "gooseegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "gooseegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Turkey Eggs</td>
                <td><%= @egginventory.last.turkeyegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "turkeyegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "turkeyegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Guinea Hen Eggs</td>
                <td><%= @egginventory.last.guineaegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "guineaegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "guineaegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              <tr>
                <td>07/23/15</td>
                <td>Quail Eggs</td>
                <td><%= @egginventory.last.quailegg %></td>
                <td>
                  <%= button_to "+1", incrementegg_path({id: @egginventory.last.id, eggtype: "quailegg" }), :class => 'willbtn-increment' %>
                </td>
                <td>
                  <%= button_to "-1", decrementegg_path({id: @egginventory.last.id, eggtype: "quailegg" }), :class => 'willbtn-decrement' %>
                </td>
                <td>
                  <%= button_to "Delete", "eggs/:id", method: :delete, data: { confirm: 'Are you sure?' },  :class => 'willbtn-delete' %>
                </td>
              </tr>
              </tr>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<br>